#ifndef TOKEN_H
#define TOKEN_H

// Enum com todos os tokens possíveis
typedef enum {
    TOKEN_IF, TOKEN_ELSE, TOKEN_WHILE, TOKEN_RETURN, TOKEN_INT, TOKEN_VOID, // Palavras reservadas
    TOKEN_PLUS, TOKEN_MINUS, TOKEN_MULT, TOKEN_DIV, TOKEN_LT, TOKEN_LTE, TOKEN_GT, TOKEN_GTE, TOKEN_EQ, TOKEN_NEQ, TOKEN_ASSIGN, // Operadores
    TOKEN_SEMICOLON, TOKEN_COMMA, TOKEN_LPAREN, TOKEN_RPAREN, TOKEN_LBRACE, TOKEN_RBRACE, TOKEN_LBRACKET, TOKEN_RBRACKET, // Símbolos especiais
    TOKEN_NUMBER, TOKEN_IDENTIFIER, TOKEN_COMMENT, TOKEN_WHITESPACE, TOKEN_EOF, // Tipos comuns
    TOKEN_ERROR, // Caso de erro léxico
    TOKEN_ID, TOKEN_NUM // Tokens para a gramática
} TokenType;

#endif
